# Generated by Django 2.2 on 2021-01-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=250),
            preserve_default=False,
        ),
    ]
