# Generated by Django 2.2 on 2021-02-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0004_auto_20210131_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='metal', max_length=10),
        ),
    ]
