# Generated by Django 2.2 on 2021-02-05 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0006_auto_20210204_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
