# Generated by Django 2.2 on 2021-02-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0007_auto_20210204_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='metal', max_length=12),
        ),
    ]
