# Generated by Django 2.2 on 2021-02-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0008_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='Metal', max_length=12),
        ),
    ]
